#!/usr/bin/env bash
# That script changes your home ip localhost to 127.0.0.2 and facebook.com to 8.8.8.8

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts